etablissementclasse_index:
    path:     /
    defaults: { _controller: "AppBundle:EtablissementClasse:index" }
    methods:  GET

etablissementclasse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:EtablissementClasse:show" }
    methods:  GET

etablissementclasse_new:
    path:     /new
    defaults: { _controller: "AppBundle:EtablissementClasse:new" }
    methods:  [GET, POST]

etablissementclasse_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:EtablissementClasse:edit" }
    methods:  [GET, POST]

etablissementclasse_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:EtablissementClasse:delete" }
    methods:  DELETE
