etsclasseniveauspecialite_index:
    path:     /
    defaults: { _controller: "AppBundle:EtsClasseNiveauSpecialite:index" }
    methods:  GET

etsclasseniveauspecialite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:EtsClasseNiveauSpecialite:show" }
    methods:  GET

etsclasseniveauspecialite_new:
    path:     /new
    defaults: { _controller: "AppBundle:EtsClasseNiveauSpecialite:new" }
    methods:  [GET, POST]

etsclasseniveauspecialite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:EtsClasseNiveauSpecialite:edit" }
    methods:  [GET, POST]

etsclasseniveauspecialite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:EtsClasseNiveauSpecialite:delete" }
    methods:  DELETE
